GET http://localhost:8010/Contacts


###
POST http://localhost:8010/Contacts
Content-Type: application/json

{
    "firstName": "First",
    "lastName": "Last",
    "phoneNumber": "3333-1111"
}

###
GET http://localhost:8010/Contacts/4eae1bd7-1480-4ccc-b92b-662aea257b3c


###
PUT http://localhost:8010/Contacts/4eae1bd7-1480-4ccc-b92b-662aea257b3c
Content-Type: application/json

{
    "firstName": "FirstUpdated",
    "lastName": "LastUpdated",
    "phoneNumber": "3333-2222"
}

###
DELETE http://localhost:8010/Contacts/4eae1bd7-1480-4ccc-b92b-662aea257b3c
